### ISSUE TITLE
Tests are failing in release mode

### ISSUE THREAD

**Issue by danielocfb** [libbpf/blazesym#44]
Here is a summary of running `cargo test --release` on c78091faab23091a6286cb5d30f3bda996c0f8a2:

```
running 25 tests
test dwarf::debug_info::tests::test_parse_abbrev ... ok
test dwarf::debug_info::tests::test_parse_cu_abbrevs ... ok
test dwarf::tests::test_decode_leb128 ... ok
test dwarf::tests::test_decode_words ... ok
test dwarf::tests::test_debug_info_parse_symbols ... FAILED
test dwarf::tests::test_run_debug_line_stmts_1 ... ok
test dwarf::tests::test_dwarf_resolver ... FAILED
test dwarf::tests::test_parse_aranges_elf ... FAILED
test dwarf::tests::test_run_debug_line_stmts_2 ... ok
test dwarf::tests::test_parse_debug_line_elf ... FAILED
test elf::tests::test_elf64_parser ... ok
test elf_cache::tests::test_cache ... ok
test elf::tests::test_elf_header_sections ... ok
test ksym::tests::ksym_resolver_load_find ... ignored, system-dependent; may fail
test ksym::tests::find_addresses_ksym ... ok
test tests::hello_world_stack ... ok
test elf::tests::test_elf64_find_address ... FAILED
test tests::load_symbolfilecfg_process ... ok
test elf::tests::test_elf64_symtab ... FAILED
test dwarf::debug_info::tests::test_unititer ... ok
test dwarf::tests::test_dwarf_find_addr_regex ... ok
test ksym::tests::find_addresses_ksym_exhaust ... ok
test ksym::tests::ksym_cache ... ok
test tests::load_symbolfilecfg_invalid_kernel ... ok
test tests::load_symbolfilecfg_processkernel ... ok

failures:

---- dwarf::tests::test_debug_info_parse_symbols stdout ----
thread 'dwarf::tests::test_debug_info_parse_symbols' panicked at 'assertion failed: result.is_ok()', src/dwarf.rs:1511:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- dwarf::tests::test_dwarf_resolver stdout ----
thread 'dwarf::tests::test_dwarf_resolver' panicked at 'index out of bounds: the len is 0 but the index is 0', src/dwarf.rs:929:27

---- dwarf::tests::test_parse_aranges_elf stdout ----
Custom { kind: NotFound, error: "Does not found the give section: .debug_aranges" }
thread 'dwarf::tests::test_parse_aranges_elf' panicked at 'assertion failed: r.is_ok()', src/dwarf.rs:1479:9

---- dwarf::tests::test_parse_debug_line_elf stdout ----
Custom { kind: NotFound, error: "Does not found the give section: .debug_line" }
thread 'dwarf::tests::test_parse_debug_line_elf' panicked at 'assertion failed: r.is_ok()', src/dwarf.rs:1355:9

---- elf::tests::test_elf64_find_address stdout ----
thread 'elf::tests::test_elf64_find_address' panicked at 'index out of bounds: the len is 7901 but the index is 7901', src/elf.rs:761:15

---- elf::tests::test_elf64_symtab stdout ----
thread 'elf::tests::test_elf64_symtab' panicked at 'index out of bounds: the len is 7901 but the index is 7901', src/elf.rs:761:15


failures:
    dwarf::tests::test_debug_info_parse_symbols
    dwarf::tests::test_dwarf_resolver
    dwarf::tests::test_parse_aranges_elf
    dwarf::tests::test_parse_debug_line_elf
    elf::tests::test_elf64_find_address
    elf::tests::test_elf64_symtab

test result: FAILED. 18 passed; 6 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.08s
```

I sincerely hope we can agree that tests shouldn't be failing depending on the build type used, that we should look into the issues and fix them

**Comment by ThinkerYzu1** [comment]
Sure! The release build is stripped.  We should move to use pre-built binary for these tests.

**Comment by ThinkerYzu1** [comment]
I discussed this with @danielocfb offline. Helper functions for tests cause the out-of-bounds errors here.  These helpers are only used by tests, not in released code. We can remove these helpers once we do tests against specific binary samples.
